version: '3.8'

services:
  web:
    build: .
    container_name: ecommerce-web
    ports:
      - "9090:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=edu_db
      - DB_USER=edu_user
      - DB_PASSWORD=edu_pass

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: edu_pass
      MYSQL_DATABASE: edu_db
      MYSQL_USER: edu_user
      MYSQL_PASSWORD: edu_pass
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
